if(NOT DEFINED RM_PROJECT_ROOT)
  get_filename_component(RM_PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(asset_check_strict FALSE)
if(DEFINED RM_ASSET_CHECK_STRICT AND RM_ASSET_CHECK_STRICT)
  set(asset_check_strict TRUE)
endif()

set(lfs_pointer_files "")
file(GLOB_RECURSE rm_png_files "${RM_PROJECT_ROOT}/resources/images/*.png")
foreach(image_file IN LISTS rm_png_files)
  file(READ "${image_file}" image_head LIMIT 80)
  if(image_head MATCHES "^version https://git-lfs.github.com/spec/v1")
    file(RELATIVE_PATH rel_path "${RM_PROJECT_ROOT}" "${image_file}")
    if(rel_path MATCHES "^resources/images/images/")
      continue()
    endif()
    list(APPEND lfs_pointer_files "${rel_path}")
  endif()
endforeach()

set(portability_path_hits "")
file(GLOB_RECURSE rm_source_files
  "${RM_PROJECT_ROOT}/src/*.cpp"
  "${RM_PROJECT_ROOT}/src/*.h"
  "${RM_PROJECT_ROOT}/src/*.qml")
list(APPEND rm_source_files
  "${RM_PROJECT_ROOT}/CMakeLists.txt"
  "${RM_PROJECT_ROOT}/resources.qrc")

foreach(src_file IN LISTS rm_source_files)
  file(READ "${src_file}" src_content)
  set(hit "")
  if(src_content MATCHES "/Users/")
    set(hit "/Users/")
  elseif(src_content MATCHES "(^|[^A-Za-z0-9_])[A-Za-z]:[/\\\\]")
    set(hit "Windows drive absolute path")
  elseif(src_content MATCHES "/home/")
    set(hit "/home/")
  endif()

  if(NOT hit STREQUAL "")
    file(RELATIVE_PATH rel_path "${RM_PROJECT_ROOT}" "${src_file}")
    list(APPEND portability_path_hits "${rel_path} (${hit})")
  endif()
endforeach()

set(qrc_resource_paths "")
set(missing_qrc_files "")
set(current_prefix "")
set(inside_xml_comment FALSE)
file(STRINGS "${RM_PROJECT_ROOT}/resources.qrc" qrc_lines)
foreach(line IN LISTS qrc_lines)
  string(STRIP "${line}" line)

  if(inside_xml_comment)
    if(line MATCHES "-->")
      set(inside_xml_comment FALSE)
    endif()
    continue()
  endif()

  if(line MATCHES "<!--")
    if(NOT line MATCHES "-->")
      set(inside_xml_comment TRUE)
    endif()
    continue()
  endif()

  if(line MATCHES "^<qresource[^>]*prefix=\"([^\"]+)\"")
    set(current_prefix "${CMAKE_MATCH_1}")
  elseif(line MATCHES "^</qresource>")
    set(current_prefix "")
  elseif(line MATCHES "^<file([^>]*)>([^<]+)</file>")
    set(file_attrs "${CMAKE_MATCH_1}")
    set(file_path "${CMAKE_MATCH_2}")
    set(abs_file_path "${RM_PROJECT_ROOT}/${file_path}")

    if(NOT EXISTS "${abs_file_path}")
      list(APPEND missing_qrc_files "${file_path}")
    endif()

    if(file_attrs MATCHES "alias=\"([^\"]+)\"")
      set(rel_resource_path "${CMAKE_MATCH_1}")
    else()
      set(rel_resource_path "${file_path}")
    endif()

    if(current_prefix STREQUAL "")
      set(full_resource_path "/${rel_resource_path}")
    elseif(current_prefix MATCHES "/$")
      set(full_resource_path "${current_prefix}${rel_resource_path}")
    else()
      set(full_resource_path "${current_prefix}/${rel_resource_path}")
    endif()

    string(REPLACE "//" "/" full_resource_path "${full_resource_path}")
    list(APPEND qrc_resource_paths "${full_resource_path}")
  endif()
endforeach()
list(REMOVE_DUPLICATES qrc_resource_paths)
list(REMOVE_DUPLICATES missing_qrc_files)

set(missing_qrc_refs "")
file(GLOB_RECURSE qml_files "${RM_PROJECT_ROOT}/src/qml/*.qml")
foreach(qml_file IN LISTS qml_files)
  file(READ "${qml_file}" qml_content)
  string(REGEX MATCHALL "qrc:/[A-Za-z0-9_./-]+" qml_refs "${qml_content}")

  foreach(qml_ref IN LISTS qml_refs)
    string(REPLACE "qrc:" "" qrc_path "${qml_ref}")
    while(qrc_path MATCHES "//")
      string(REPLACE "//" "/" qrc_path "${qrc_path}")
    endwhile()
    if(NOT qrc_path MATCHES "^/")
      set(qrc_path "/${qrc_path}")
    endif()

    # QML 模块内部资源由 src/qml/qml.qrc 单独声明。
    if(qrc_path MATCHES "^/qml/")
      continue()
    endif()
    # 以分隔符结尾的路径会在运行时继续拼接，不按完整资源路径检查。
    if(qrc_path MATCHES "/$" OR qrc_path MATCHES "_$")
      continue()
    endif()

    list(FIND qrc_resource_paths "${qrc_path}" qrc_idx)
    if(qrc_idx EQUAL -1)
      file(RELATIVE_PATH rel_qml_file "${RM_PROJECT_ROOT}" "${qml_file}")
      list(APPEND missing_qrc_refs "${rel_qml_file}: ${qml_ref}")
    endif()
  endforeach()
endforeach()
list(REMOVE_DUPLICATES missing_qrc_refs)

set(found_error FALSE)

if(lfs_pointer_files)
  if(asset_check_strict)
    set(found_error TRUE)
    message(SEND_ERROR "[asset-check] Detected Git LFS pointer files under resources/images. Run 'git lfs pull' or restore assets before build.\n  - ${lfs_pointer_files}")
  else()
    message(WARNING "[asset-check] Detected Git LFS pointer files under resources/images. Build continues in non-strict mode.\n  - ${lfs_pointer_files}")
  endif()
endif()

if(portability_path_hits)
  set(found_error TRUE)
  message(SEND_ERROR "[asset-check] Detected absolute local paths in source files. Use Qt resources or relative paths instead.\n  - ${portability_path_hits}")
endif()

if(missing_qrc_refs)
  set(found_error TRUE)
  message(SEND_ERROR "[asset-check] QML references missing from resources.qrc.\n  - ${missing_qrc_refs}")
endif()

if(missing_qrc_files)
  set(found_error TRUE)
  message(SEND_ERROR "[asset-check] resources.qrc references files that do not exist in the repo.\n  - ${missing_qrc_files}")
endif()

if(found_error)
  message(FATAL_ERROR "Asset validation failed.")
endif()

message(STATUS "[asset-check] Passed")
